### ISSUE TITLE
Add security descriptors to OpenAPI specifications.

### ISSUE THREAD

**Issue by jhernand** [innabox/fulfillment-api#14]
Add security descriptions to the OpenAPI specifications, for example:

```yaml
/api/fulfillment/v1/cluster_orders:
  post:
    operationId: ClusterOrders_Place
    security:
      - openIdConnect:
        - openid
        - profile
```

And a security component:

```yaml
components:
  securitySchemes:
    openIdConnect:
      type: openIdConnect
      openIdConnectUrl: https://.../.well-known/openid-configuration
```
